package lc.q389.FindtheDifference;
/*
 * 389. Find the Difference
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 * 
 */

public class FindtheDifference {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
	
		
	}
	
//	30.53%
	 public static char findTheDifference(String s, String t) 
	    {
		 	char res = t.charAt(t.length()-1);
		 	for(int i =0; i<s.length();i++)
		 	{
		 		res ^= s.charAt(i);
		 		res ^= t.charAt(i);
		 	}
		 	return res;
	    }
	 
//	 38.18%
	 public static char findTheDifference1(String s, String t)
	 {
		 char res = 'a';
		 int[] alphabet = new int[26];
		 for(int i =0; i< s.length();i++)
		 {
			 alphabet[s.charAt(i)-'a']--;
			 alphabet[t.charAt(i)-'a']++;
		 }
		 alphabet[t.charAt(t.length()-1)-'a']++;
		 for(int i =0; i<26;i++)
		 {
			 if(alphabet[i]!=0)
				 res = (char)(i+'a');
		 }
		 return res;
	 }
	 
//	 87.86%
	 public static char findTheDifference2(String s, String t) 
	    {
	        char ans = 'a';
			char[] chS = s.toCharArray();
			char[] chT = t.toCharArray();
			for(char x: chT)
				ans += x;
			
			for(char y: chS)
				ans -=y;
			
			 ans = (char) (ans-97);
			return ans;
//			this only works because t contains all char's in s and has one more
	   }
	 
//	 71.62%
	 public static char findTheDifference3(String s, String t)
	 {
		 char res = 'a';
		 int[] alphabet = new int[26];
		 for(char e:s.toCharArray())
		 {
			 alphabet[e-'a']--;
		 }
		 for(char e:t.toCharArray())
		 {
			 alphabet[e-'a']++;
		 }
		 for(int i =0; i<26;i++)
		 {
			 if(alphabet[i]!=0)
				 res = (char)(i+'a');
		 }
		 return res;
	 }

}
